### ISSUE TITLE
[soracom-uptime.md] サンプルコードに無いWioCellular.getPdpContext()の説明文がある

### ISSUE THREAD

**Issue by susami-lab** [SeeedJP/wio_cellular#16]
Wio_BG770A/examples/soracom/soracom-uptime.md
には、

> SORACOMプラットフォームのAPNを設定します。 APNは一度設定するとセルラーモジュールで記憶するので、WioCellular.getPdpContext()で未設定かどうかを確認してからAPNを設定するようにします。 APNを設定するときは電話の機能レベルを最小にしてセルラー通信を止めます。

とありますが、下記実際のサンプルコードには、上記記述が見当たりません。
サンプルコードもしくは、サンプルコード解説の誤記ではないでしょうか。
examples/soracom/soracom-uptime/soracom-uptime.ino

**Comment by matsujirushi** [comment]
ご指摘のとおり、サンプルコード変更後に説明を変更し忘れていました。
説明を直します。

**Comment by matsujirushi** [comment]
https://github.com/SeeedJP/Wiki/commit/20318cfbd713668157cdb9f5b5558e683bb3e508
