### ISSUE TITLE
[soracom-uptime-lp.md] イベント駆動型プログラミングの図がわかりにくい

### ISSUE THREAD

**Issue by susami-lab** [SeeedJP/wio_cellular#17]
Wio_BG770A/examples/soracom/soracom-uptime-lp.md
の、イベント駆動型プログラミングの図に関する提案です。

![41](https://github.com/user-attachments/assets/7b9543ca-ccbc-41b8-8bcf-1f018bf0ba33)

## ■1点目
図右側に、
==MeasureSem
WioCellular.setPsm()
xTimerStart(xTimerCreate(CellularStartSem))

== CellularStartSem
measure()
send()

とありますが、正しくは、
==MeasureSem
measure()
send()

== CellularStartSem
WioCellular.setPsm(
TimerStart(xTimerCreate(CellularStartSem))

ではないでしょうか。

## ■2点目
現状、文章でのセマフォの説明の順番（下記）と、図の説明の順番が異なるため、同じ順番にすると理解しやすいと感じました。
CellularWorkSemセマフォ
CellularStartSemセマフォ
MeasureSemセマフォ

**Comment by matsujirushi** [comment]
ご指摘のとおり、図中のコードが間違っていました。
直します。

あわせて、ご提案いただいた表記順に変更します。

**Comment by matsujirushi** [comment]
https://github.com/SeeedJP/Wiki/commit/eac54d0971af5da5ddfa762c94e314f300b26518
