### ISSUE TITLE
groveコネクタを利用する際に電源供給開始のコードが必要なことをドキュメントに追加してほしい

### ISSUE THREAD

**Issue by kenichiro-kimura** [SeeedJP/wio_cellular#18]
groveコネクタに接続したセンサーが、センサー側のサンプルコードではうまく動かず少し迷いました。

groveコネクタについてはハードウェアマニュアルに「電源供給時にはLEDがONになる」との記載はありますので、動作しない際にLEDを確認 → 電源を入れる必要があると認識 → Wioのサンプルスケッチを見るという形で解決はできるものの、できればユーザーマニュアルに何か記載があると気づきやすくなってありがたいです。

また、ハードウェアマニュアルにデフォルトがOFFである記載もあるとより親切かと思いました。

ご検討いただけますと幸いです。

**Comment by matsujirushi** [comment]
> https://zenn.dev/showm001/articles/2024-12-01-01

**Comment by matsujirushi** [comment]
Issue起票ありがとうございます！

取り急ぎ、ハードウェアマニュアルとナレッジベースに記入しました。
https://github.com/SeeedJP/Wiki/commit/fc0c215a81a71b18ae56ce50c28b14ea4dbe9f9f

**Comment by matsujirushi** [comment]
> また、ハードウェアマニュアルにデフォルトがOFFである記載もあるとより親切かと思いました。

SeeedJP nRF52 Boardsのマニュアルに書く事項と思いますが、SeeedJP nRF52 Boardsのマニュアルが無いので、、、
様子見させてください。🙇‍♂️
