### ISSUE TITLE
アナログ入力の計算式の解説がわかりにくい

### ISSUE THREAD

**Issue by susami-lab** [SeeedJP/wio_cellular#24]
https://seeedjp.github.io/Wiki/Wio_BG770A/examples/grove/grove-rotary-angle-sensor.html
に書かれた下記表現が、最初わかりませんでした。
> analogRead()の値を/ 16383 * 0.6f * 6するとアナログ入力の電圧(0〜3.3[V])になります。 さらに3.3で割ると、正規化した値(0〜1)になります。

サンプルコードだけでなく、解説ページにも、
・0.6Vが基準電圧であること
・1/6がゲインであること
・14ビットの場合は、3.6Vのとき16383になること
・該当センサーにおいて、回転量minのとき0Vが、回転量maxのとき3.3Vが出力されるため、3.3Vで割ることで、0-1に正規化されること
の説明があると、わかりやすいと感じました。

**Comment by matsujirushi** [comment]
ご連絡ありがとうございます。
ご提案のとおり、説明を追記しようと思います。

**Comment by matsujirushi** [comment]
変更しました。
https://github.com/SeeedJP/Wiki/commit/e72e281ec688c07359af7a0904ba845aa909f0ee

いかがでしょうか？
@susami-lab
